//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatchNext.DataAccess.Ef.CoreModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class ShowVideos
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public string Site { get; set; }
        public int Size { get; set; }
        public int ShowsId { get; set; }
    }
}
