//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatchNext.DataAccess.Ef.CoreModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Shows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shows()
        {
            this.ShowImages = new HashSet<ShowImages>();
            this.ShowVideos = new HashSet<ShowVideos>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Overview { get; set; }
        public double Rating { get; set; }
        public string Slug { get; set; }
        public int TraktApiId { get; set; }
        public int TvdbApiId { get; set; }
        public string ImdbApiId { get; set; }
        public Nullable<int> TmdbApiId { get; set; }
        public Nullable<int> TvRageApiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<ShowImages> ShowImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<ShowVideos> ShowVideos { get; set; }
    }
}
