//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatchNext.DataAccess.Ef.CoreModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class WhatchNextModelContainer : DbContext
    {
        public WhatchNextModelContainer()
            : base("name=WhatchNextModelContainer")
        {
            Shows = Set<Shows>();
            ShowImages = Set<ShowImages>();
            ShowVideos = Set<ShowVideos>();
            MostPopularShows = Set<MostPopularShows>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Shows> Shows { get; set; }
        internal virtual DbSet<ShowImages> ShowImages { get; set; }
        internal virtual DbSet<ShowVideos> ShowVideos { get; set; }
        internal virtual DbSet<MostPopularShows> MostPopularShows { get; set; }
        public virtual DbSet<ShowData> ShowDatas { get; set; }
        public virtual DbSet<RankingPopularShows> RankingPopularShows { get; set; }
    }
}
